# Generated by Django 4.2.1 on 2023-05-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_user_profile_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
    ]
