# Generated by Django 4.2.1 on 2023-05-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_profile_date_of_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="user",
        ),
    ]
