# Generated by Django 4.2.1 on 2023-05-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_username_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="blank_propic.png", upload_to="profile_images"
            ),
        ),
    ]
