# Generated by Django 4.2.1 on 2023-05-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_profile_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="media/blank-propic.png", upload_to="profile_images"
            ),
        ),
    ]
