# Generated by Django 4.2.1 on 2023-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_profile_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="second_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
