# Generated by Django 4.2.1 on 2023-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
